nelmio_api_doc:
    documentation:
        servers:
            - url: http://localhost:8080/api
              description: API over HTTP

        info:
            title: Api Vico
            description: Api to create client and rate project vico
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []